### ISSUE TITLE
installation/ gameplay

### ISSUE THREAD

**Issue by Hdisx2** [RimWorldCCLTeam/CommunityCoreLibrary#106]
I followed all the directions step by step and when i activated CCL my game froze, afterward I restarted because that's what the page said to do and when i did the screen for rimworld went black and now i can't play please help.

**Comment by ForsakenShell** [comment]
Some people have had issues with "dirty installs" of either the core game or CCL.  Be sure to run and exit RimWorld at least once before activating any mods so the game can create all the necessary config files.

**Comment by ForsakenShell** [comment]
Is this still an issue?  Haven't heard anything back.

**Comment by Hdisx2** [comment]
I'm sorry and nothing was loading after a few weeks while still checking in  to see if I got any answers so I deleted all of the extra stuff and now it won't let me redownload it

**Comment by ForsakenShell** [comment]
The core game has sometimes issues with old versions of it's own config files.  The best bet would be to do a completely clean install.  A14D just came out on steam (no sendowl e-mail sent) and CCL is about to be released for the new build.

**Comment by ForsakenShell** [comment]
Based on lack of info to reproduce and lack of feedback, closing this as it seems it's an installation issue.

If the problem persists and you can provide new info then feel free to add more to this and I'll re-open it.
