### ISSUE TITLE
minor: Injecting CompPowerTrader into walls throws out of bounds error on connection check.

### ISSUE THREAD

**Issue by FluffierThanThou** [RimWorldCCLTeam/CommunityCoreLibrary#114]
Not sure this one is fixable, as it would require a specific catch for injecting power comps into things that are outside of the normally buildable region. Either way, here goes;

> Got ThingsListAt out of bounds: (250, 0, 83)

**Comment by ForsakenShell** [comment]
I don't think we need to fix this one as it's only purpose is to demonstrate how to inject ThingComps.

It's the xml that's important, not it's functionality (in so far as the CompPowerTrader and walls go).
