### ISSUE TITLE
Bad Load order

### ISSUE THREAD

**Issue by mothringer** [RimWorldCCLTeam/CommunityCoreLibrary#119]
On loading game (linux version) I get an incorrect error message "A bad load order has been detected. Community Core Library is not the second mod loaded."

I get this even if CCL and core are the only two activated mods.

**Comment by ForsakenShell** [comment]
I'm guessing you got CCL from Steam.  This has been addressed in preparation for our official Steam release.

**Comment by mothringer** [comment]
Yes, and when I eventually thought to download it separately, the problem
was fixed.

**Comment by ForsakenShell** [comment]
We have not done an official release on steam.  We will post in main forum thread when we do the steam release.
