### ISSUE TITLE
Prisoners won't eat

### ISSUE THREAD

**Issue by finnaintza** [RimWorldCCLTeam/CommunityCoreLibrary#120]
0.14 - When I have CCL enabled, prisoners will not pick up meals or food left in their prison cell, to the point of starvation.

**Comment by Jotalandia** [comment]
I'm having the same problem. 
[CCL bug.zip](https://github.com/RimWorldCCLTeam/CommunityCoreLibrary/files/367716/CCL.bug.zip)

**Comment by ForsakenShell** [comment]
Already reported and fixed - #118
