### ISSUE TITLE
Prisoners don't eat

### ISSUE THREAD

**Issue by sarina800** [RimWorldCCLTeam/CommunityCoreLibrary#121]
Taken prisoners don't eat after they're fully healed and be provided food into their cell. They just wander around until they die from malnutrition.  This only occurs when the CCL is initialized, not the vanilla tweaks one.

[output_log.txt](https://github.com/RimWorldCCLTeam/CommunityCoreLibrary/files/367842/output_log.txt)

![rimworld_prisonernoms](https://cloud.githubusercontent.com/assets/10735230/16900829/b20ffa5c-4bfe-11e6-8866-64d393481750.PNG)

**Comment by sarina800** [comment]
I see previous closed issues of this context. Though I'm testing it right now and it still persists :/

**Comment by ForsakenShell** [comment]
Already reported, fixed and closed.  #118, #120
