### ISSUE TITLE
Enhancement request: Refrigerator structure

### ISSUE THREAD

**Issue by drumanagh** [RimWorldCCLTeam/CommunityCoreLibrary#133]
This would work exactly like a refrigerated hopper currently does, except it wouldn't be a hopper (so no feeding items into other structures), and thus it wouldn't cause the 'hopper is not connected' message in the UI.

Since it's a useful variation of existing stuff but not really a "core" feature, it might be best suited to go into Vanilla Tweaks rather than the CCL core package.

**Comment by ForsakenShell** [comment]
The Vanilla Tweaks doesn't add anything new and it never will.  That is the job of mods using CCL.
