### ISSUE TITLE
MCM not saving settings after reload

### ISSUE THREAD

**Issue by The-Key** [RimWorldCCLTeam/CommunityCoreLibrary#135]
The MCM isn't saving any settings. The settings work until I restart Rimworld, after which everything goes back to default. I deactivated every other mod so my load order is Core>CCL. In the attached log
I loaded the game, changed a couple minimap settings, and then closed the game.
[output_log.txt](https://github.com/RimWorldCCLTeam/CommunityCoreLibrary/files/384821/output_log.txt)

**Comment by ForsakenShell** [comment]
I had to make some changes for minimaps to save their per-game data.  I may have to make similar changes to the MCM system.  Thanks for the info.  :)

**Comment by ForsakenShell** [comment]
I tried but can't reproduce this error.

Your log file indicates there is a problem with something though.  Some mod is creating invalid UV coords for a texture.

> Texture rectangle is out of bounds

I would check your mods by individually disabling each one until this message disappears and then report it to the mod author.
