### ISSUE TITLE
Designator injector does not handle ReverseDesignatorDatabase

### ISSUE THREAD

**Issue by micktu** [RimWorldCCLTeam/CommunityCoreLibrary#143]
Meaning gizmos are not displayed for selected things, unllike vanilla ones.

If it's intentional, please provide a config option to also add designators to `ReverseDesignatorDatabase`.

**Comment by ForsakenShell** [comment]
A14 made the required fields public so CCLs implementation is now just a wrapper and is now deprecated.  It will be removed in A15 (assuming that it isn't made private again).

Take a look at my ESM - Mine Vein and ESM - Smooth Wall for how to get them to work properly.  The CCL code is basically a wrapper now but it should work.

https://github.com/ForsakenShell/Es-Small-Mods/blob/master/MineVein/SpecialInjectors/SpecialInjector_MineVein.cs
https://github.com/ForsakenShell/Es-Small-Mods/blob/master/SmoothWall/SpecialInjectors/SpecialInjector_SmoothWall.cs
