### ISSUE TITLE
Chars standing around.

### ISSUE THREAD

**Issue by biship** [RimWorldCCLTeam/CommunityCoreLibrary#144]
I've tried official 0.14.1 and self-compiled dev branch 8/1/16. I get this reoccuring error for all chars. They just stand around. Sorry if it is not caused by CCL. 
[output_log.zip](https://github.com/RimWorldCCLTeam/CommunityCoreLibrary/files/394252/output_log.zip)

**Comment by ForsakenShell** [comment]
Turns out this is a Tofu related issue with the Vegetable Garden mod.
