### ISSUE TITLE
Detours issue?

### ISSUE THREAD

**Issue by biship** [RimWorldCCLTeam/CommunityCoreLibrary#148]
https://github.com/RimWorldCCLTeam/CommunityCoreLibrary/commit/3713546d6ae659a98ebebbe4fc6a7499c1ab2fb1

is giving me this:

Community Core Library :: Injection Controller :: Initialization :: Errors during injection
    (Error) :: Detours :: Source MethodInfo is null
    Error injecting 'CommunityCoreLibrary.DetourInjector'

I assume it's coming from a call to TryDetourFromTo. How do I find what is causing it?

EDIT: (actually, I dont know if it's new since that commit. I just didn't see this error yesterday)

**Comment by biship** [comment]
The minimap is empty/blank. Resizing, moving, resetting to default work however.

**Comment by ForsakenShell** [comment]
Fixed
