### ISSUE TITLE
Minimap is doing art

### ISSUE THREAD

**Issue by mrofa** [RimWorldCCLTeam/CommunityCoreLibrary#150]
So this is a issue is on default settings of minimap, didnt test other settings.
Everythin starts allright, i see my midgets runing in panic, squieerls to avoid, bears to hunt and so on.
But after like 10-15 mins of game it starts to bug out. First are the positions of animals, not sure about visitors since i eat them all, they are showed in wrong places on minimap, some are in the moutains, some are in a middle of my colony.
Rectangle that shows the player camera position on the map clone itself, so if i zoom ut abit insted of one rectagle i see 2 or 3 and so one.
And the maps stops refreshing itself fully, meaning everything that moves starts to draw lines, making preety nice art, but making map completly unreadable.

**Comment by ForsakenShell** [comment]
Can you provide a screen shot of the minimap (please crop you 4k display to just the minimap ;) ).

Also, does the log file contain anything regarding the issue?

**Comment by FluffierThanThou** [comment]
@mrofa pretty please?

**Comment by mrofa** [comment]
Save/Load thing, sorry guys dont look at email to often  
I did mention it to ekie on slack i think, did some more tests and this thing only happen when i save/load without closing the game client.
Not sure how to delete this issue
