### ISSUE TITLE
Diseases chance per year in Help menu is wrong

### ISSUE THREAD

**Issue by Moumix3** [RimWorldCCLTeam/CommunityCoreLibrary#153]
The chance per year for Diseases in the Help menu for Biomes shows a very high percentage, which is probably (hopefully!!) not the right one. :)

This issue exists for all biomes, not just for Boreal Forest.

![ss 2016-08-12 at 01 31 53](https://cloud.githubusercontent.com/assets/11393498/17609408/d3195224-602c-11e6-93df-9bd48ea263e6.png)

**Comment by FluffierThanThou** [comment]
heh, yeah that don't look right :P

**Comment by FluffierThanThou** [comment]
fixed in f43f37b1ce27212f67cfdecad7fd5271769281f6
