### ISSUE TITLE
Lastest CCL update on RimWorld

### ISSUE THREAD

**Issue by theazureazoth** [RimWorldCCLTeam/CommunityCoreLibrary#167]
Alright, I tried to follow the directions, removed the last version, unzipped the user file into the core folder, but in the instructions it says to enable the library but in the mod list I do not see the core library so i must have done something wrong.
I am new to using mods so take it as it is.

Edit: most mods i use are those that you can use from steam, this is the first time i have tried to put anything into the game core files

**Comment by ForsakenShell** [comment]
You don't put anything into the "core game files", you put them in the mod directory.

Your games mod directory should look like this:

/Mods/Core
/Mods/Community Core Library
/Mods/Community Core Library - Mod Tweaks
/Mods/Community Core Library - Vanilla Tweaks

etc

**Comment by theazureazoth** [comment]
I will give it a try and report back if i screw up which is a high probability

**Comment by theazureazoth** [comment]
Alright, seems to be working properly, if i have anymore trouble i will make a new topic, many thanks
