### ISSUE TITLE
emptyu black box in middle of screen

### ISSUE THREAD

**Issue by Commissar0617** [RimWorldCCLTeam/CommunityCoreLibrary#176]
i get am empty black box in the middle of the screen (this is on current release, with me using the most up to date version of rimworld). i prevents any interaction with the ui. i have to alt-f4 out of the game.

**Comment by TechnologicApe** [comment]
I get the same thing. It may be from CCL not being for A15

**Comment by ForsakenShell** [comment]
No additional information provided or clarification whether using the mod on an unsupported build (one not listed as being compatible with), closing as a result.
