### ISSUE TITLE
Designators & prefs.ini

### ISSUE THREAD

**Issue by skyarkhangel** [RimWorldCCLTeam/CommunityCoreLibrary#26]
When del Prefs.xml from config folder and then start Rimworld, designators in order menu does not appear. So, Rimworld auto-create this file, restarting the game solves problem.. But not very convenient for new players.

upd. Prefs.xml not .ini

**Comment by ForsakenShell** [comment]
I can not reproduce this error.  Please provide more details.

**Comment by ForsakenShell** [comment]
Changing languages without a restart is the problem.  CCL builds a lot of data when RimWorld starts which is language dependant.  For now, must restart RimWorld on language setting change.  Well see what can be done about this in the future.

**Comment by ForsakenShell** [comment]
This may be fixed by #41, needs testing

**Comment by skyarkhangel** [comment]
in CCL 12.4, problem is still there. Changing languages without a restart - make designators the invisible.

**Comment by Karel-Kroeze** [comment]
I guess technically we should re-initialize all assets on mod reload. That's going to be a fairly huge operation though.

**Comment by ForsakenShell** [comment]
There are more issues at play than simply CCL needing to re-initialize it's assets.  The core game has bugs itself with changing certain options and mod order.

Solution:  Restart RimWorld.
