### ISSUE TITLE
HelpDefs with long names are word-wrapped and clipped

### ISSUE THREAD

**Issue by ForsakenShell** [RimWorldCCLTeam/CommunityCoreLibrary#39]
The label for help defs with long names use a smaller font, but word-wrapping still clips the text.

![helpmenu_multiline_cutoff](https://cloud.githubusercontent.com/assets/12161749/10407163/655616fc-6ea4-11e5-88ad-38a2550dba27.png)

**Comment by Karel-Kroeze** [comment]
I'll take a look at making the rects bigger when the label doesn't fit.

**Comment by ForsakenShell** [comment]
Resolved in #41
