### ISSUE TITLE
Feature Request:  Advanced Research in the Research menu

### ISSUE THREAD

**Issue by ForsakenShell** [RimWorldCCLTeam/CommunityCoreLibrary#44]
Add an additional tab to the research menu to show advanced research projects if any exist.  If none exist, this tab can be hidden as per the help menu not adding empty categories.

On the research menu, it wouldn't show the "research" and "insta-finish" buttons, but should show progress which would be the aggregate score of the required research.

**Comment by Karel-Kroeze** [comment]
Added in ee6802f6e96b5368056e374efba8df4c0aad93ae
