### ISSUE TITLE
Reduce solar panel output during rain, fog, different seasons, increase turbine output during storms.

### ISSUE THREAD

**Issue by Asmageddon** [RimWorldCCLTeam/CommunityCoreLibrary#49]
Not only because it makes sense, but because it balances out the other power consumption changes.

The numbers I propose are relatively mild:
- 90% solar power for fog.
- 60% solar power for thunderstorms.
- 15% solar power for eclipses. Because they are not a total blackout.
- 97.5/100/97.5/95% solar power for Spring/Summer/Autumn/Winter.
- Random fluctuations of +/-3% solar power thorough the day.
- 133% turbine power for thunderstorms.

**Comment by ForsakenShell** [comment]
Wind turbines are already affected by storms in the default code and will put out up to 150% power (3000W vs the 2000W "normal" max).

As to the solar, that sounds like something for a separate mod than CCL.  CCL isn't about making core changes so much as providing tools for modders to do common tasks in a "standard" way.  That being said, I would love to see a mod which does such a thing.  :)

**Comment by Asmageddon** [comment]
It SHOULD be a CCL Tweaks thing, because it contains power consumption changes that make power management trivial compared to vanilla.

**Comment by Karel-Kroeze** [comment]
I agree with E that this isn't really in the remit of CCL. Closing for now, might get back to doing this in a separate mod at a later date.
