### ISSUE TITLE
Cook stove disappears when built.

### ISSUE THREAD

**Issue by UristMcKerman** [RimWorldCCLTeam/CommunityCoreLibrary#53]
That's it.

**Comment by Karel-Kroeze** [comment]
What makes you think this is a CCL problem? Do you have an output_log.txt or failing that a screenshot of the error?

Having never had this happen in testing and with no other reports, I'm tempted to say it's either not related to CCL, or a rare interaction between mods that we won't be able to reproduce without more info.

**Comment by Karel-Kroeze** [comment]
https://www.reddit.com/r/RimWorld/comments/3z0j4e/cooking_stove_disappears_when_using_ccl_vanilla/

Wrong mod order, closing
