### ISSUE TITLE
Certain conditions cause Research Menu to throw null reference errors

### ISSUE THREAD

**Issue by ForsakenShell** [RimWorldCCLTeam/CommunityCoreLibrary#57]
I'm not yet sure of the exact cause of this, it seems to stem from the help def generator and improper cross-referencing in the research menu (no help def).

Screen shots showing this error can be seen here in the [A2B](https://github.com/A2Bcorp/RW_A2B/issues/53) issue report.

**Comment by isistoy** [comment]
Hello,

The output_log below contains several successful attempts at loading a saved game generated with ccl and clutter, and then, the creation of a new one, in which research window sends exceptions (I shrinked it, repetitive exceptions made the file > 20MB).

I then closed RW and tried reproduce, thinking it was a pb when creating a new game, but no more errors in the next game's creations.

[output_log - Copy.txt](https://github.com/RimWorldCCLTeam/CommunityCoreLibrary/files/131899/output_log.-.Copy.txt)

[Picture](http://puu.sh/n9EfV/53a21e7387.jpg)

**Comment by mrofa** [comment]
This couse is when you have a existing mod that uses ccl research and then add a mod, any mod that dont even use ccl. Until you dont restar rimworld client this error will happen

**Comment by chaosjockey** [comment]
I have the same errors even after restoring my backup and removing the mod, I can't load my colony but I can create new ones just fine.

Actually, every time I close rimworld completely after using CCL I can't load that colony. Yes, I do leave it open for hours.

**Comment by ForsakenShell** [comment]
chaosjockey, I'm not sure how that helps us with this.  You don't add anything new to help narrow down this issue and introduce an unrelated issue.  This isn't a forum, it's an issues tracker, please provide details which can be helpful (logs, steps to which will definitely trigger the error, etc).

**Comment by chaosjockey** [comment]
I apologize, I honestly thought you would like to know that there are other people having the same issue, perhaps if more people were to speak up you'd feel the urgency to fix such a wonderful mod which you so graciously provide us with. The thing with posting redundant issues, ESPECIALLY on Github, they get deleted and then you get flak for it.

So, I'm sorry, I didn't realize you wanted me to provide an identical error log, the only redundancy I like to see is in my backups. I've already disabled CCL, I can now save, load, and even close my game. I'll keep an eye on your github for updates but I'm not going to restart my game each time I close the client.

Thanks.

P.S.
This is as much as a 'forum' post as my previous comment.
"This couse is when you have a existing mod that uses ccl research and then add a mod, any mod that dont even use ccl. Until you dont restar rimworld client this error will happen"

**Comment by ForsakenShell** [comment]
We do want to know about other people with the same issue, but we also want people only to post if they have new, relevant, information.  "Me too" posts don't help and only clutter the issue.  I'm not trying to give you flak or be a jerk.  :)

As to the "urgency," fluffy and I both have spent months trying to figure this bug out.  Neither of us can reproduce it reliably and that is the problem - we don't know the triggers for the issue.  It's not that we aren't trying to find the issue, but without being able to reproduce it, we can't find the cause.

Regarding logs and additional information, your error log wouldn't be "identical" and the more logs we can get from more people the easier it will be to find.  One log from one person is almost no help, two from two people will be little help, 100 from 100 people would be fantastic.  Ideally, we'd want you to zip your entire mods directory, your ModsConfig.xml and send those to us.  But, we don't want people sending us 100MB zips so we don't ask for that.  If you're using unmodified mods (ie, you downloaded them, didn't modify them yourself) then we can download suspect mods to examine ourselves (provided we can find them).

That your game constantly disables mods when you restart sounds like a larger issue than CCL.  You may want to follow these forum threads with similar issues:
https://ludeon.com/forums/index.php?topic=17777.0
https://ludeon.com/forums/index.php?topic=17869.0

P.S.
Again, not trying to be a jerk.  :)

**Comment by FluffierThanThou** [comment]
Closing this as research is getting a full rewrite.
