### ISSUE TITLE
CCL Breaking normal+colored lights

### ISSUE THREAD

**Issue by jaidens111** [RimWorldCCLTeam/CommunityCoreLibrary#58]
full log : http://pastebin.com/cb1xyLkY
All I had to do was place the blueprint for a light and let a colonist build it, not replicable with god mode on but lights still won't be built if it is on.

**Comment by Karel-Kroeze** [comment]
Are you sure you've got both CCL itself AND the CCL Vanilla Tweaks enabled and updated to the latest version?

**Comment by ForsakenShell** [comment]
Having taken a quick look at that log, it would appear that CCL is not loaded.  The vanilla tweaks requires the core library to be loaded first.  If you don't see a line which reads "Community Core Library :: v0.12.x" (where "x" is the release) then it's not loaded.

**Comment by ForsakenShell** [comment]
No additional feedback means this is probably resolved.
