### ISSUE TITLE
Add "Restart now?" pop-up after mods are reloaded

### ISSUE THREAD

**Issue by Karel-Kroeze** [RimWorldCCLTeam/CommunityCoreLibrary#59]
I'm getting tired of telling people to reload after making mod changes.

**Comment by ForsakenShell** [comment]
I've been thinking of this too, perhaps detouring the start/load buttons to force CCL to re-init if the mod menu is opened.

**Comment by NoImageAvailable** [comment]
I could definitely get behind a popup menu that offers the option to immediately close the game, i.e. have it go "Mod changes were made, restart the game now? Restart/Cancel"

**Comment by ForsakenShell** [comment]
Written and working, closing issue.
