### ISSUE TITLE
No feedback on detour failure

### ISSUE THREAD

**Issue by NoImageAvailable** [RimWorldCCLTeam/CommunityCoreLibrary#61]
Currently, if you detour multiple methods and one of them fails, you get absolutely no indication that something is wrong, no errors, etc. it just silently fails in the background. The only way to notice is ingame when things aren't working as they're supposed to. 

What's more, one broken detour seems to break all other detours as well so its very easy to end up with a completely borked game and not even realize it.

Would be good if there was either some internal error reporting or if the method returned a bool to allow modders to use constructs like if (!detourFromTo(...)) Log.Error("MyMod failed to detour...")

**Comment by ForsakenShell** [comment]
There is a "Verbosity" tag in the ModHelperDef which controls how much spam is sent to the log.  Increase the verbosity for your mod to see additional information.

0.12.7 has had the default level of verbosity increased for modders release to "Injections" (from "Validation").
