### ISSUE TITLE
Allow inheritance of MCMInjectionSet / make them like ThingComp

### ISSUE THREAD

**Issue by Alicecomma** [RimWorldCCLTeam/CommunityCoreLibrary#63]
As it stands one could not add variables to the MCMInjectionSet since structs can not be inherited from. This means a mod author would have to write a separate def or similar to add variables to be used in the injection set which makes the entire thing a bit useless for more complicated MCM menus.

I would like the class to be abstract/virtual or similar, maybe even make them more like ThingComps by turning public List<MCMInjectionSet> ModConfigurationMenus into a public List<MCMInjectionSetProperties> ModConfigurationMenuProperties; with MCMInjectionSetProperties.menuClass.

**Comment by ForsakenShell** [comment]
This is certainly do-able, my method has been to have a static class with the config data for the mod but I can see where defining defaults in xml itself would be useful.  This is why I did modders pre-releases though, to get feedback on small changes and tweaks before the official release.

**Comment by ForsakenShell** [comment]
The MCMInjectionSet is now a class which can be extended to allow modders to add data to the xml.

CCL updated and released at 0.12.7.1
