### ISSUE TITLE
Cannot grow hop plant after researching brewing

### ISSUE THREAD

**Issue by snake3276120** [RimWorldCCLTeam/CommunityCoreLibrary#77]
As per title. 
Mods used:
1. CCL
2. CCL Vanilla tweak 
3. Edb colonist bar
4. Edb prepare carefully
5. High calibre
6. Expanded prosthetics and organ engineering
7. A dog says...

**Comment by ForsakenShell** [comment]
Unable reproduce, seems to work fine with just CCL Core and VT.

Possible mod conflict or indirectly fixed when adding sowResearchPrerequisites handling to ResearchProjectDef_Extensions.

**Comment by snake3276120** [comment]
It is probably caused by one of my mods. After I updated a bunch of them, it is working right now. Please kindly close this issue.
