### ISSUE TITLE
Orbital trade hangs after clicking "Accept"

### ISSUE THREAD

**Issue by snake3276120** [RimWorldCCLTeam/CommunityCoreLibrary#78]
After clicking "Accept" for an orbital trade, the game does nothing but the UI of orbital trade hangs. You can still use ESC to cancel the trade, but I am not able to do any buy/sell (except for those items that are too cheap for receiving a silver) from orbital trader.

Mods used:
1. CCL
2. CCL Vanilla tweak 
3. Edb colonist bar
4. Edb prepare carefully
5. High calibre
6. Expanded prosthetics and organ engineering
7. A dog says...

**Comment by ghost** [comment]
Just wanted to drop a note that I'm having the same issue.

I'm using:
CCL
CCL Vanilla tweaks
RT Storage
[T] Terraforming
Mad Skills - Tiered
Floor Lights

Included this in case it was helpful or relevant.
![debuglog](https://cloud.githubusercontent.com/assets/3449708/14711511/8de69e88-07a7-11e6-81f0-b08d509e5978.png)
