### ISSUE TITLE
Vanilla tweaks not saving power

### ISSUE THREAD

**Issue by tommargar** [RimWorldCCLTeam/CommunityCoreLibrary#82]
I created a new world, started a new colony, and placed an autodoor with god mode. The power usage told me it's still using 50 W, instead of the proposed 10 W. The Vanilla Tweaks were both loaded as third after CCL, and as last mod in line. 

I noticed this behavior first in my existing colony. First had CCL installed incorrectly and then later activated it on my existing colony and was wondering why the power runs dry so quickly.

[Archiv.zip](https://github.com/RimWorldCCLTeam/CommunityCoreLibrary/files/232366/Archiv.zip)

**Comment by ForsakenShell** [comment]
Based on your Player.log, there are several mods which are not A13 compatible.  You should report those errors to the developers of those mods.

Small selection of errors:

> Loader exceptions:
>    => System.TypeLoadException: Could not load type 'CommunityCoreLibrary.SpecialInjector' from assembly 'Community Core Library, Version=0.12.2.0, Culture=neutral, PublicKeyToken=null'.
> Could not find a type named StorageSearch.Injector_StorageSearch
> 
> I AM HERE:
>    at System.Environment.get_StackTrace()
>    at FollowMe.Bootstrap..ctor()
>    ...
> 
> Tried to get SoundDef named AmbientNightInsects_Standard, but sound defs aren't loaded yet (is it a static variable initialized before play data?).
> Could not resolve cross-reference: No RimWorld.IncidentDef named Disease_Flu found to give to RimWorld.BiomeDiseaseRecord RimWorld.BiomeDiseaseRecord
> ...
> 
> Exception loading list from XML: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
>   at System.Collections.Generic.List`1+Enumerator[Verse.CrossRefLoader+WantedRef].VerifyState () [0x00000] in <filename unknown>:0 
>   at System.Collections.Generic.List`1+Enumerator[Verse.CrossRefLoader+WantedRef].MoveNext () [0x00000] in <filename unknown>:0 
>   at Verse.CrossRefLoader.RegisterListWantsCrossRef[ThingDef](System.Collections.Generic.List`1 wanterList, System.String targetDefName) [0x00000] in <filename unknown>:0 
>   at Verse.XmlToObject.ListFromXml[ThingDef](System.Xml.XmlNode listRootNode) [0x00000] in <filename unknown>:0 
> XML:
> <thingDefs><li>Fruitdrink</li></thingDefs>

You are going to have to disable all your mods and enable them one-by-one to find the offending mods.
