### ISSUE TITLE
Social Relax Errors?

### ISSUE THREAD

**Issue by Tjstretchalot** [RimWorldCCLTeam/CommunityCoreLibrary#88]
I am having troubles narrowing down where this error is coming from, as it happens quite inconsistently. I _think_ it may have to do with creating a table and then setting it to not be a gather spot anymore. 

Here is what the error looks like, once it starts happening it happens every time they try to "relax socially". 

![screenshotlu](https://cloud.githubusercontent.com/assets/931176/14939211/847a9cea-0ef1-11e6-9629-aef79c99f1eb.png)

**Comment by Tjstretchalot** [comment]
Also, upon closing rimworld and reopening it and reopening the colony:

![screenshot2](https://cloud.githubusercontent.com/assets/931176/14939219/1b74e5e2-0ef2-11e6-8ae5-6a874126166f.png)

**Comment by ForsakenShell** [comment]
Seems issue #81 is still an issue.

**Comment by Tjstretchalot** [comment]
Nevermind, you did fix it. I got my mod folders confused.

Thank you!

**Comment by ForsakenShell** [comment]
Ahh yes, if I would have looked closer, that screenshot shows CCL v0.13.1, this was fixed in v0.13.1.1
