### ISSUE TITLE
CCL Mod "installing" problem

### ISSUE THREAD

**Issue by Fymothar** [RimWorldCCLTeam/CommunityCoreLibrary#90]
I have a problem with CCL. Not sure why it is occuring but everytime I try to install it (mark it in mods section and place it under the core) and go back to main menu, all of the button labels dissapears, only the links stay. Can't start a game or even quit it. Anyone knows why it is happening?

**Comment by ForsakenShell** [comment]
We need your output log (not a screenshot of the debug window) before anything else.

We can't help you when you provide no information.  Please review [this](https://ludeon.com/forums/index.php?topic=16599.msg179403#msg179403) forum post on how to report bugs.

**Comment by Fymothar** [comment]
Thanks for help, as I thought. Nevermind it started to work, somehow.
