### ISSUE TITLE
Restart and saved game data folder with spaces

### ISSUE THREAD

**Issue by RemingtonRyder** [RimWorldCCLTeam/CommunityCoreLibrary#98]
So I tried out the restart feature.

However from what I can guess it doesn't handle save game data folders which contain a space e.g. C:\Users\Marvinator\Documents\my games\RimWorld Alpha 13 - after restart, the same game data folder is re-overridden to C:\Users\Marvinator\Documents\my.

Steps to duplicate:
- Create or have a RimWorld shortcut which points to a saved game folder other than the default and contains a space.
- Start RimWorld using this shortcut.
- Enter Mods screen.
- Leave Mods screen.
- Choose Restart when prompted.

I tested these steps using a non-spaced savegame data folder and that worked fine, by the way, so it's a workaround I can use for now.

[output_log.txt](https://github.com/RimWorldCCLTeam/CommunityCoreLibrary/files/275400/output_log.txt)

Hope this helps!

**Comment by ForsakenShell** [comment]
Will look at quoting the passed arguments for the next release.
